controller_manager:
  ros__parameters:
    use_sim_time: True
    
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    sandwich_bot_base_controller:
        type: diff_drive_controller/DiffDriveController
      # type: pid_diff_drive_controller/PIDDiffDriveController
sandwich_bot_base_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    # write_op_modes: ["motor_controller"]
    
    wheel_separation: 0.160
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # left_wheel_pid_params:
    #     p: 0.001
    #     i: 0.0
    #     d: 0.0
    #     i_clamp_max: 1.0
    #     i_clamp_min: -1.0
    #     antiwindup: false

    # right_wheel_pid_params:
    #     p: 0.001
    #     i: 0.0
    #     d: 0.0
    #     i_clamp_max: 1.0
    #     i_clamp_min: -1.0
    #     antiwindup: false

    odom_frame_id: odom
    # is odometry with the base footprint is accurate?
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 500.0
    use_stamped_vel: false
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true