rtabmap:
  ros__parameters:
    frame_id: base_footprint
    subscribe_stereo: true
    subscribe_depth: false
    subscribe_rgbd: false
    queue_size: 30
    
    Stereo/MaxDisparity: '128'
    stereo_approx_sync:  true
    map_negative_poses_ignored: true
    Rtabmap/TimeThr: '700'
    Grid/DepthDecimation: '4'
    Grid/FlatObstacleDetected: 'true'
    Kp/MaxDepth: '0'
    Kp/DetectorStrategy: '6'  
    Vis/EstimationType: '1' 
    Vis/MaxDepth: '0'
    RGBD/CreateOccupancyGrid: 'true'  

    # SURF/HessianThreshold: 1000
    # LccBow/MinInliers: 10
    # LccBow/EstimationType: 1
    # LccReextract/Activated: true
    # LccReextract/MaxWords: 500
    # LccReextract/MaxDepth: 10 